[build]
  publish = "dist"
  command = "npm run build"

# API Proxy
[[redirects]]
  from = "/api/*"
  to = "https://ais-dev-5nzkpaledyax3iiyxzslxu-394997633999.asia-southeast1.run.app/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
